Repository LHL-FocusPocus/FocusPocus, pull requests merged in 2020-05, with the labels that each got.

#9 Feature/register
  client/.babelrc.json
  client/package-lock.json
  client/package.json
  client/public/imgs/landing-bg.png
  client/public/imgs/landing-bg2.png
  client/public/imgs/landing.png
  client/public/imgs/wand.png
  client/public/imgs/wild-sea.png
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Landing.jsx
  client/src/components/LogoText.jsx
  client/src/components/SignUp.jsx
  client/src/index.css
  client/src/logo.svg
  package-lock.json
  server/server.js
Labels: enhancement

#12 Server/database setup
  server/db/schema/01_users.sql
  server/db/schema/02_websites.sql
  server/db/schema/03_blacklists.sql
  server/db/schema/04_browse_times.sql
  server/db/schema/05_quotas.sql
  server/db/seeds/01_users.sql
  server/db/seeds/02_websites.sql
  server/db/seeds/03_blacklist.sql
  server/db/seeds/04_browse_times.sql
  server/db/seeds/05_quotas.sql
Labels: question

#30 Client/dashboard navbar drawer
  client/public/imgs/multitasking.jpg
  client/src/App.js
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Graph1.jsx
  client/src/components/Graphs/Graph2.jsx
  client/src/components/Graphs/Graph3.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/Navbar.jsx
  client/src/components/SignUp.jsx
  client/src/index.js
  server/routes/userRoutes.js
Labels: proof of concept

#34 Extension/auto gradual replacement
  chrome-extension/background.js
  chrome-extension/changePictures.js
  chrome-extension/changeVideos.js
  chrome-extension/helpers.js
Labels: enhancement

#44 Client/analytics graphs
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Graph1.jsx
  client/src/components/Graphs/Graph2.jsx
  client/src/components/Graphs/Graph3.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Graphs/Shameboard.jsx
  client/src/helpers/loading.js
  client/src/helpers/toMinutes.js
  client/src/hooks/useApplicationData.js
  client/src/index.css
  client/src/reducers/application.js
  server/db/seeds/02_websites.sql
  server/routes/dataRoutes.js
Labels: enhancement

#56 Client/options page
  client/src/App.css
  client/src/App.js
  client/src/components/Blacklisted.jsx
  client/src/components/BlacklistedCards.jsx
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Graphs/Shameboard.jsx
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/LogoText.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/SignUp.jsx
  client/src/helpers/removeProtocol.js
  client/src/hooks/useApplicationData.js
  client/src/hooks/useFormFields.js
  client/src/index.css
  client/src/reducers/application.js
  server/db/schema/03_blacklists.sql
  server/helpers/dbHelper.js
  server/routes/dataRoutes.js
  server/routes/userRoutes.js
Labels: proof of concept

#76 Client/navbar
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Dashboard.jsx
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/Navbar.jsx
  client/src/components/Options.jsx
  client/src/components/SignUp.jsx
  client/src/hooks/useApplicationData.js
  client/src/reducers/application.js
Labels: enhancement

#75 Client/add chart titles
  client/src/components/Blacklisted.jsx
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Graphs/Shameboard.jsx
  client/src/components/Options.jsx
Labels: enhancement

#84 Client/top blacklisted dnd
  client/package-lock.json
  client/package.json
  client/public/imgs/magic-trick.png
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/components/Blacklisted.jsx
  client/src/components/BlacklistedCards.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/TopBlacklistCards.jsx
  client/src/components/TopBlacklisted.jsx
  client/src/hooks/useApplicationData.js
  client/src/utils/constants.js
  server/db/seeds/03_blacklist.sql
  server/helpers/dataProcessor.js
  server/helpers/dbHelper.js
  server/routes/dataRoutes.js
Labels: proof of concept

#89 Server/fix disable ==> client state not setting object properly
  client/src/App.js
  client/src/components/Blacklisted.jsx
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Navbar.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/SignUp.jsx
  client/src/hooks/useApplicationData.js
  client/src/reducers/application.js
  server/routes/userRoutes.js
Labels: bug

#90 Automatic quota adjuster
  chrome-extension-react/public/index.html
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/components/Dashboard.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/TopBlacklistCards.jsx
  client/src/hooks/useApplicationData.js
  client/src/reducers/application.js
  server/helpers/dbHelper.js
  server/routes/userRoutes.js
Labels: enhancement

#91 Extension/replace text - Replace nouns on the page with another word (i.e. 'snake')
  chrome-extension-react/public/POSTagger.js
  chrome-extension-react/public/background.js
  chrome-extension-react/public/changePictures.js
  chrome-extension-react/public/changeText.js
  chrome-extension-react/public/changeVideos.js
  chrome-extension-react/public/helpers.js
  chrome-extension-react/public/images/get_started128.png
  chrome-extension-react/public/images/get_started16.png
  chrome-extension-react/public/images/get_started32.png
  chrome-extension-react/public/images/get_started48.png
  chrome-extension-react/public/lexer.js
  chrome-extension-react/public/lexicon.js_
Labels: enhancement

#93 Implement websocket for dashboard
  client/package-lock.json
  client/package.json
  client/src/hooks/useApplicationData.js
  client/src/reducers/application.js
  server/package-lock.json
  server/package.json
  server/routes/extensionRoutes.js
  server/server.js
Labels: enhancement

#96 Client/fonts titles
  chrome-extension-react/public/index.html
  client/public/imgs/genie-cloud.png
  client/public/imgs/genie.png
  client/public/imgs/gold-wand-border.png
  client/public/imgs/gold-wand.png
  client/public/imgs/hat-wand.png
  client/public/imgs/hat.png
  client/public/imgs/hat.xcf
  client/public/imgs/landing-bg2.png
  client/public/imgs/logo.png
  client/public/imgs/logo2.png
  client/public/imgs/logo3.png
  client/public/imgs/magic-trick-border.png
  client/public/imgs/wand2.png
  client/public/imgs/wild-sea.png
  client/public/imgs/wood-wand.png
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Blacklisted.jsx
  client/src/components/BlacklistedCards.jsx
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Graphs/Shameboard.jsx
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/LogoText.jsx
  client/src/components/Navbar.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/SignUp.jsx
  client/src/components/TopBlacklisted.jsx
  client/src/helpers/formatNavbarText.js
  client/src/index.css
  client/src/reducers/application.js
Labels: enhancement

#102 Allow users to set their own urls for img, video, and noun replacements
  chrome-extension-react/package-lock.json
  chrome-extension-react/public/background.js
  chrome-extension-react/public/changePictures.js
  chrome-extension-react/public/changeText.js
  chrome-extension-react/public/changeVideos.js
  client/src/App.js
  client/src/components/Blacklisted.jsx
  client/src/components/Customization.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/helpers/isUrl.js
  server/helpers/dbHelper.js
  server/routes/userRoutes.js
Labels: enhancement

#104 Quota bug conditional display
  chrome-extension-react/src/components/Blacklist.jsx
  client/package-lock.json
  client/package.json
  client/src/components/Blacklisted.jsx
  client/src/components/Customization.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Graphs/Shameboard.jsx
  client/src/components/Navbar.jsx
  client/src/components/Options.jsx
  client/src/helpers/isUrl.js
Labels: enhancement

#108 Client/root routing
  client/public/google1105a46a0a558fd2.html
  client/src/App.js
  client/src/components/Dashboard.jsx
  client/src/components/Landing.jsx
  client/src/components/Navbar.jsx
Labels: bug

#110 Client/extension privacy policy
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/LogoText.jsx
  client/src/components/SignUp.jsx
Labels: enhancement

#105 Register bug
  client/src/components/Landing.jsx
  client/src/components/SignUp.jsx
  server/db/schema/05_quotas.sql
  server/helpers/dataProcessor.js
  server/helpers/dbHelper.js
  server/routes/userRoutes.js
Labels: bug

#117 Misc fixes
  chrome-extension-react/public/images/logo3.png
  chrome-extension-react/src/components/Home.jsx
  chrome-extension-react/src/index.css
  client/package-lock.json
  client/package.json
  client/public/imgs/genie-cloud.png
  client/public/imgs/genie.png
  client/public/imgs/gold-wand-border.png
  client/public/imgs/gold-wand.png
  client/public/imgs/hat.xcf
  client/public/imgs/magic-trick-border.png
  client/public/imgs/multitasking.jpg
  client/public/imgs/wand.png
  client/public/imgs/wand2.png
  client/public/imgs/wood-wand.png
  client/src/App.css
  client/src/App.js
  client/src/components/Blacklisted.jsx
  client/src/components/BlacklistedCards.jsx
  client/src/components/Customization.jsx
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Graphs/Shameboard.jsx
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/LogoText.jsx
  client/src/components/Navbar.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/SignUp.jsx
  client/src/components/TopBlacklistCards.jsx
  client/src/components/TopBlacklisted.jsx
  client/src/helpers/formatNavbarText.js
  client/src/helpers/validEmail.js
  client/src/hooks/useApplicationData.js
  client/src/index.css
  client/src/reducers/application.js
  client/src/routes.js
  server/db/seeds/01_users.sql
  server/db/seeds/04_browse_times.sql
  server/helpers/dataProcessor.js
  server/helpers/dbHelper.js
  server/routes/apiRoutes.js
  server/routes/dataRoutes.js
  server/routes/rootRoutes.js
  server/routes/userRoutes.js
  server/server.js
Labels: enhancement

#124 Responsive design
  client/src/App.css
  client/src/components/Blacklisted.jsx
  client/src/components/Dashboard.jsx
  client/src/components/Graphs/DailyQuotaUsed.jsx
  client/src/components/Graphs/Donut.jsx
  client/src/components/Graphs/Leaderboard.jsx
  client/src/components/Graphs/LineGraph.jsx
  client/src/components/Graphs/Radial.jsx
  client/src/components/Landing.jsx
  client/src/components/Login.jsx
  client/src/components/LogoText.jsx
  client/src/components/Navbar.jsx
  client/src/components/Options.jsx
  client/src/components/QuotaSlider.jsx
  client/src/components/SignUp.jsx
  client/src/components/TopBlacklisted.jsx
Labels: enhancement
